apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "angelai.fullname" . }}-{{ .Values.color }}
  labels:
    app: {{ include "angelai.name" . }}
    color: {{ .Values.color }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "angelai.name" . }}
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ include "angelai.name" . }}
        color: {{ .Values.color }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: angelai-config
            items:
              - key: config.yaml
                path: config.yaml
