apiVersion: v1
kind: ResourceQuota
metadata:
  name: trading-quota
  namespace: trading
spec:
  hard:
    pods: "10"
    requests.cpu: "5"
    requests.memory: 10Gi
    limits.cpu: "10"
    limits.memory: 20Gi
